### ISSUE TITLE
Controlhost

### ISSUE THREAD

**Issue by hpatoio** [ricfrank/ansible-devmarche#1]
Ciao, I'm wondering why you create a `controlhost` and then, from it, you provision the other boxes instead of provision them directly from the hosting machine. Which are the benefits ?

**Comment by ricfrank** [comment]
Hi. 

This was a simple way for run configuration on windows/mac/linux users. This is a setup that i created for a local users group meeting where every users could run ansible on his machine without have ansible installed. The benefits are all related only for "demo reasons".

At work i provision directly from my hosting machine.

If it can help you, here

https://github.com/ideatosrl/vagrant-php-template

you can see our development configuration with Vagrant and Ansible.

Is it a good answer ? :).

**Comment by hpatoio** [comment]
Yes, it is !  :+1:  
I thought that was the reason but I wanted to be sure !
